name: "Build"

on:
  workflow_call:
    inputs:
      version:
        description: "Build Version"
        type: string
        required: true

jobs:
  build:
    name: "Build - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          #- os: macos-latest
          #  name: macos-arm64
          - os: macos-15-intel
            name: macos-amd64
          - os: ubuntu-latest
            name: linux-amd64
          #- os: ubuntu-24.04-arm
          #  name: linux-arm64
          - os: windows-latest
            name: windows-amd64

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install task"
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: go-task/task

      - name: "Download Artifact"
        if: ${{ !github.event.release.prerelease }}
        uses: actions/download-artifact@v7
        with:
          name: client
          path: dist/client

      - name: "Generate Manifest"
        run: python assets/manifest.py

      - name: "Debug Artifact"
        continue-on-error: true
        shell: bash
        run: ls -lAhR dist

      - name: "Build Package"
        run: task build

      - name: "Debug Output"
        continue-on-error: true
        shell: bash
        run: ls -lAhR out

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: linux-installer
          path: out

      - name: "Upload Release"
        if: ${{ github.event_name == 'release' }}
        uses: cssnr/upload-release-action@v1
        with:
          globs: out/*
          overwrite: true
